name: Build
run-name: ${{ github.actor }} is building the project  #github.actor is my name

on: [push]                                       # the condition trigger CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Check out repository code                     # official checkout, pull current code to runner 
        uses: actions/checkout@v4
        with:
          submodules: recursive

        # for ccache. also need to write in cmake
      - name: Restore shaderc cache
        uses: actions/cache@v3
        with:
          path: /usr/local/lib
          key: shaderc-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            shaderc-${{ runner.os }}-
          
          # restore ktx
      - name: Restore KTX cache
        uses: actions/cache@v3
        with:
          path: ./_deps/ktx-build  # why this folder
          key: ktx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ktx-${{ runner.os }}-

        # download google test
      - name: Install Google Test
        run: |
          mkdir -p external/gtest
          wget -O external/gtest.tar.gz https://github.com/google/googletest/archive/release-1.12.1.tar.gz
          tar -xzf external/gtest.tar.gz -C external/gtest --strip-components=1

      - name: Verify Google Test headers
        run: ls -l /path/to/googletest/include/gtest/gtest.h

      - name: Notify repository has been cloned
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install GLFW
        run: |
          sudo apt update
          sudo apt install -y libglfw3 libglfw3-dev

      - name: Install  GLM
        run: sudo apt install -y libglm-dev
      
      - name: Install Assimp
        run: sudo apt install -y libassimp-dev

      - name: Install glsl
        run: |
          if [! -f /usr/local/bin/glslc ]; then
            sudo apt update
            sudo apt install -y git cmake python3 python3-pip build-essential
            git clone https://github.com/google/shaderc.git
            cd shaderc
            python3 ./utils/git-sync-deps
            mkdir build
            cd build
            cmake -GNinja ..
            ninja
            sudo ninja install
            echo "export PATH=/usr/local/bin:$PATH" >> $HOME/.bashrc
            source $HOME/.bashrc
          else
            echo "shaderc already installed, skip build"
          fi


      # save caches
      - name: Save shaderc cache
        uses: actions/cache@v3
        with:
          path: /usr/local/lib
          key: shaderc-${{ runner.os }}-${{ github.sha }}

      - name: Save KTX cache
        uses: actions/cache@v3
        with:
          path: ./_deps/ktx-build
          key: ktx-${{ runner.os }}-${{ github.sha }}

      - name: Verify KTX cache
        run: ls -l ./_deps/ktx-build


      - name: Install stb_image
        run: |
          mkdir -p external/stb
          wget -O external/stb/stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h
          wget -O external/stb/stb_image_write.h https://raw.githubusercontent.com/nothings/stb/master/stb_image_write.h

      - name: Check build.sh exists
        run: ls -l build.sh

      - name: Make build.sh executable
        run: chmod +x build.sh
          
      - name: Check Vulkan SDK version
        run: vulkaninfo | grep "Vulkan Instance Version"

      - name: Build project
        run: sh build.sh